# 该服务开放的端口号
server:
    port: 1000

eureka:
    instance:
        #主机名
        hostname: discovery
        #强制eureka服务使用IP地址注册而不是hostname主机名
        prefer-ip-address: false
    server:
        # 关闭自我保护模式（缺省为打开）
        # 关闭状态下进入服务管理界面有红色错误提示
        enable-self-preservation: true
        # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
        eviction-interval-timer-in-ms: 60000
    client:
        #这两种写法都可以
        # 设置是否将自己作为客户端注册到注册中心（缺省true）
        # 这里为不需要（查看@EnableEurekaServer注解的源码，会发现它间接用到了@EnableDiscoveryClient）
        registerWithEureka: false
        #register-with-eureka: false

        # 设置是否从注册中心获取注册信息（缺省true）
        # 因为这是一个单点的EurekaServer，不需要同步其它EurekaServer节点的数据，故设为false
        #fetch-registry: false
        fetchRegistry: false

        # 在未设置defaultZone的情况下，注册中心在本例中的默认地址就是http://127.0.0.1:1100/eureka/
        # 但奇怪的是，启动注册中心时，控制台还是会打印这个地址的节点：http://localhost:8761/eureka/
        # 而实际服务端注册时，要使用1100端口的才能注册成功，8761端口的会注册失败并报告异常
        serviceUrl:
            #注册中地址所有服务注册的地址
            # 实际测试：若修改尾部的eureka为其它的，比如/myeureka，注册中心启动没问题，但服务端在注册时会失败
            # 报告异常：com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
            defaultZone: http://discovery:${server.port}/eureka/
