# 该服务开放的端口号
server:
    port: 2000

# 指定发布的微服务名（以后调用时，只需该名称即可访问该服务）
spring:
    application:
        name: shine-service

eureka:
    instance:
        instance-id: ${spring.application.name}:${server.port}
        # 设置微服务调用地址为IP优先（缺省为false）
        prefer-ip-address: true
        # 心跳时间，即服务续约间隔时间（缺省为30s）
        lease-renewal-interval-in-seconds: 5
        # 发呆时间，即服务续约到期时间（缺省为90s）
        lease-expiration-duration-in-seconds: 15
    client:
        # 开启健康检查（依赖spring-boot-starter-actuator）
        #healthcheck:
        #    enabled: true
        # 指定服务注册中心的地址
        serviceUrl:
            defaultZone: http://127.0.0.1:1000/eureka/
