server:
    port: 8989
eureka:
    client:
        serviceUrl:
            defaultZone: http://discovery:1000/eureka/
turbine:
    app-config: shine-web
    cluster-name-expression: new String('default')
    combine-host-port: true